### ISSUE TITLE
[Suggestion] - Add the ability to replace the whole RGB color in hex

### ISSUE THREAD

**Issue by matteo-de-carli** [luisfontes19/vscode-swissknife#10]
Hi, I'd like to suggest a quality of life improvement.
At the moment, the RGB to HEX (and viceversa) only works correctly when just the color values are selected.
I think that converting the colors even when the whole color is selected (including the function name and brackets) would be more useful.

Thanks in advance
Matteo

**Comment by luisfontes19** [comment]
So I changed the way the color conversions work to match the other conversions:

- It will look in the entire text (or just the selected) for a color pattern: #FFFFFF or rgb(1,2,3), rgba(1,2,3,4) depending on the script invoked
- When converting from rgb(a) to hex, if the selected content is like: `255,255,255` it will convert it, otherwise it needs to have the function like `rgb(255,255,255)`

let me know if it works 😁

again, if you don't want to wait for the new release you can download a build from [github actions](https://github.com/luisfontes19/vscode-swissknife/actions/runs/2488094288)

**Comment by matteo-de-carli** [comment]
Thank you so much!

From an initial test, the conversion with function name seembs to be working.
Though I've noticed that the alpha conversion from HEX to RGB seems not to map the hexadecimal value to a scale from 0 to 1

ex: the color #6667AB05 gets converted to "rgba(102,103,171,5)", which is correct, except for the alpha channel, which as said requires to be mapped to a decimal value from 0 to 1 (in this case the result would be 0.3125 or 0.3 if approximated)

Thanks again!

**Comment by matteo-de-carli** [comment]
Okay, now the hex→RGB mapping works, but it seems that the conversion from hex to rgb for the alpha channel is broken. From the few tests I've done, it seems that everything below 1 in the RGB alpha channel gets converted to hex value 00, while rgb alpha 1 gets correctly converted to 1.

Let me know if I need to do more testing on it :)

**Comment by luisfontes19** [comment]
hey,

I noticed that a bit after pushing the changes...
This motivated me to finally start writing unit tests (still a WIP), but now i believe its working fine. [Let me know](https://github.com/luisfontes19/vscode-swissknife/actions/runs/2494713502)

**Comment by matteo-de-carli** [comment]
It's okay, I'm just trying to help improving this already amazing extension!
By the way, after a little bit of testing it seems that the alpha channel conversion from HEX to RGB is working fine now.
I've though noticed that the opposite isn't working as expected: `rgba(114, 138, 76, 0.5)` gets converted to `#728A4C00`, where the color channels are correct, but the alpha is wrong. It gives the right result only if you set non-decimal values in the rgba formats (either 0 or 1).

Hope that helps :)

**Comment by luisfontes19** [comment]
Hmm can you double check that you tried with the latest build I sent in the previous comment? (https://github.com/luisfontes19/vscode-swissknife/actions/runs/2494713502) This seems to be working properly there, your value gets converted to #728a4c80

**Comment by matteo-de-carli** [comment]
My bad, I forgot to install the latest build
Everithing works fine now 😅

Thanks for the reminder!
