### ISSUE TITLE
Feature: Custom Decorators - show decorators on the directory if the file is decorated inside of it

### ISSUE THREAD

**Issue by JackVeromeev** [luisfontes19/vscode-swissknife#12]
If I add the decorator to a file and then fold the directory, I cannot see if it has or has no files decorated. If the project is big it becomes hard to find what files you marked to check/review.

You can probably add the sidebar section showing all decorated files/directories as alternative solution.

Thank you a lot for this extension anyway!

**Comment by luisfontes19** [comment]
Hi JackVeromeev,

Thanks for the feedback, it makes total sense. 

I'm going with the second option as the first one will not solve the issue. On big projects you see a folder with a decorator but you need to go deep and deep until you find the file decorated. Also the extension allows to decorate entire folders it wouldn't be intuitive

Already started working on the panel and it looks like this:
<img width="271" alt="image" src="https://user-images.githubusercontent.com/5262312/185344163-1699c560-f0c7-4199-bd79-bb63f8cb9062.png">

For now its going to be just a simple list which may not be the best approach when you have tons of nested folders but with time i'll convert this to a tree. 
For now, to be able to provide that feature fast i'm going with the list.

**Comment by luisfontes19** [comment]
Implemented in [b621bdd](https://github.com/luisfontes19/vscode-swissknife/commit/b621bdd820c3d3a6f01e6ddf948f5c87d23a07a6)
