### ISSUE TITLE
No log to output window from HTTP server

### ISSUE THREAD

**Issue by JoostAB** [luisfontes19/vscode-swissknife#14]
I started local http server and did some requests, but nothing is logged to my output window.

OS: WIndows 10
Swissknife version: 1.7.0
VSCode: 1.73.1

**Comment by luisfontes19** [comment]
Hi @JoostAB Can you check if the server is running by doing a request to it? 

Also, can you confirm that you changed the output to the swissknife output?


![image](https://user-images.githubusercontent.com/5262312/201911272-1ba5b7b2-117d-4cd3-abf1-2ba362156642.png)

**Comment by JoostAB** [comment]
I'm sorry, I was not able to check into this for a while... But you are right. My stupid mistake ;)
Closing this issue...
