### ISSUE TITLE
Shortcut for MD5?

### ISSUE THREAD

**Issue by ChR-iSz** [luisfontes19/vscode-swissknife#16]
It is possible to create a shortcut to replace String with your MD5 function ?

**Comment by luisfontes19** [comment]
Hey @ChR-iSz 

Im not sure if I understand what you need...


You want to find a specific string and replace all occurrences of it with an md5 digest for them?

If thats the case thats already possible... Select the string what you and press ctrl+shift+l (or cmd+shift+l on a mac), this will allow you to edit all occurrences of that word at once. Then just invoke the swissknife command palette and select the MD5 script.

If you just want to MD5 a specific word just select that work and run the MD5 script from swissknife. 

Have in mind that by default swissknife will apply a script to the entire editor's content if no text is selected, but in case the text is selected it will only apply to that text, and if you have multi selection with multi cursors it will apply that script to all the selections at once
