### ISSUE TITLE
Extension host terminated unexpectedly

### ISSUE THREAD

**Issue by 0xHacktor** [luisfontes19/vscode-swissknife#4]
Swissknife v1.3.1, available from the Microsoft Visual Studio Code Marketplace, crashes immediately with the error message "Extension host terminated unexpectedly". The last update in the Microsoft Visual Studio Code Marketplace was in April 2021 and the most recent commit on GitHub was in February 2022. I can reproduce the issue on Manjaro Linux and Mac OS using the latest version of Microsoft Visual Studio Code. The issue started with an update of Microsoft Visual Studio Code in February 2022. Maybe updating Swissknife in the official Microsoft Visual Studio Code Marketplace could help.

**Comment by luisfontes19** [comment]
Can you send me the logs of the error? Can you try to disable other extensions first?

I'm using VScode 1.65.0 on MacOS with swissknife 1.3.1 and can't reproduce the issue

**Comment by 0xHacktor** [comment]
Log see below. Since I disabled the Regex Workbench extension, Swissknife is working fine again. But as Regex Workbench does not interfere with other extensions, so I'm still curious what's going on. Maybe an issue with Regex Workbench?
[vscode-app-1646898265750.log](https://github.com/luisfontes19/vscode-swissknife/files/8221467/vscode-app-1646898265750.log)

**Comment by luisfontes19** [comment]
Interesting...

Okey, swissknife is failing getting crypto currency rates from https://api.cryptonator.com. They added cloudflare on the api, and now can only be accessed by browser. Why it is breaking with regexworkbench i don't understand 😅

Ill try to find an alternative to this

**Comment by luisfontes19** [comment]
I temporarily disabled the crypto prices script. 
I'll release the new version meanwhile. 

Thanks
