### ISSUE TITLE
[SUGGESTION] RGBA conversion

### ISSUE THREAD

**Issue by matteo-de-carli** [luisfontes19/vscode-swissknife#8]
Hi, 
seeing that the extension has RGB/HEX conversion, would it be possible to add RGBA/HEX (in #rrggbbaa format) conversion? I think it could be really useful

Thanks in advance,
Matteo

**Comment by luisfontes19** [comment]
Hi Matteo,

Makes total sense. I’ll only be able to tackle this next week, but will get it done. 

In the meantime if you’re interested, you can easily create a user script to do it without going through the source code of the extension. Check the docs [here](https://github.com/luisfontes19/vscode-swissknife/blob/master/data/custom_scripts.md)

**Comment by matteo-de-carli** [comment]
That's amazing! Thank you so much :)
I'll be waiting for the next release 😁
